@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class StudentRoster
Class Student
Class StudentName
Class AcademicLevel
Class TuitionSubjects
Class StudentPhone

Class Homework
Class Title
Class TuitionSubject
Class DueDate
Class HomeworkStatus
Class Score
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" StudentRoster
StudentRoster --> "*" Student
Student *--> "2" StudentName
Student *--> AcademicLevel
Student *--> TuitionSubjects
Student *--> "2" StudentPhone
Student *--> "*" Homework

TuitionSubjects --> "1..*" TuitionSubject
Homework *--> Title
Homework *--> TuitionSubject
Homework *--> DueDate
Homework *--> HomeworkStatus
Homework *--> "0..1" Score
@enduml
